# Generated by Django 3.2 on 2021-05-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='post',
            name='body0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body3',
            field=models.TextField(blank=True),
        ),
    ]
