# Generated by Django 3.2 on 2021-05-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_auto_20210513_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='BlogPost',
        ),
    ]
